// ==========================================
// SUPABASE CONFIGURATION - EXAMPLE FILE
// ==========================================
// 
// This is an example configuration file.
// DO NOT edit this file directly!
//
// To setup your own deployment:
// 1. Copy this file and rename to: supabase_config.dart
// 2. Replace the placeholder values with your actual Supabase credentials
// 3. Get your credentials from: https://app.supabase.com/project/_/settings/api
//
// SECURITY WARNING:
// - NEVER commit supabase_config.dart to Git (it's already in .gitignore)
// - NEVER share your Supabase credentials publicly
// - Use ANON key only (never service_role key in client apps)
//
// ==========================================

class SupabaseConfig {
  // Your Supabase project URL
  // Example: https://abcdefghijk.supabase.co
  static const String supabaseUrl = 'https://YOUR_PROJECT_ID.supabase.co';
  
  // Your Supabase anon/public key (safe to use in client apps)
  // Find it in: Supabase Dashboard → Project Settings → API → anon/public
  static const String supabaseAnonKey = 'YOUR_SUPABASE_ANON_KEY_HERE';
  
  // ==========================================
  // IMPORTANT NOTES:
  // ==========================================
  // 
  // 1. ANON KEY vs SERVICE ROLE KEY:
  //    - Use ANON KEY for client-side apps (Flutter web/mobile)
  //    - NEVER use service_role key in client apps (it bypasses RLS)
  //
  // 2. ROW LEVEL SECURITY (RLS):
  //    - All tables should have RLS enabled
  //    - RLS policies protect your data even if anon key is exposed
  //    - Review policies regularly in Supabase Dashboard
  //
  // 3. ADMIN ACCESS:
  //    - Admin credentials are NOT stored in code
  //    - Admin access is managed via database (admin_users table)
  //    - Only authorized emails can access admin panel
  //
  // 4. OAUTH CONFIGURATION:
  //    - Configure OAuth in Supabase Dashboard → Authentication → Providers
  //    - Redirect URL: https://YOUR_PROJECT_ID.supabase.co/auth/v1/callback
  //
  // ==========================================
}
